services:
  ai_model:
    build:
      context: ./ai-model
    container_name: ai_model
    volumes:
      - .:/app/code
      - ./outputs:/app/outputs
      - ./configs:/app/configs
    tty: true                           # Optional: allows manual debugging