version: '3.9'

services:
  ai_model:
    build:
      context: ./ai-model
    volumes:
      - ./scanner:/app/scanner
    container_name: ai_model


  gitleaks:
    image: zricethezav/gitleaks
    container_name: gitleaks
    volumes:
      - ./scanner:/scan
      - ./configs/gitleaks.toml:/gitleaks.toml
    command: detect --no-git --source=/scan --config=/gitleaks.toml --report-path=/scan/gitleaks.json


  yara:
    image: blacktop/yara
    container_name: yara
    volumes:
      - ./scanner:/scan
      - ./configs/yara_rules:/rules
    command: yara -r /rules/custom_rules.yar /scan

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data


volumes:
  sonar_data:
