version: '3.9'

services:
  ai_model:
    build:
      context: ./ai-model
    container_name: ai_model
    volumes:
      - ./scanner:/app/scanner
      - ./configs/yara_rules:/rules   # ✅ Add this line



  gitleaks:
    image: zricethezav/gitleaks
    container_name: gitleaks
    volumes:
      - ./scanner:/scan
      - ./configs/gitleaks.toml:/gitleaks.toml
    command: detect --no-git --source=/scan --config=/gitleaks.toml --report-path=/scan/gitleaks.json


  yara:
    image: blacktop/yara
    container_name: yara
    volumes:
      - ./scanner:/scan
      - ./configs/yara_rules:/rules
    command: ["sh", "-c", "yara -r /rules/test_secrets.yar /scan"]