services:
  ai_model:
    build:
      context: ./ai-model
    container_name: ai_model
    volumes:
      - ./target_repo:/app/code         # ✅ User's code to scan
      - ./outputs:/app/outputs          # ✅ Reports directory
      - ./configs:/app/configs          # ✅ YARA rules, Gitleaks config, etc.
    tty: true                           # Optional: allows manual debugging