name: Salus Repo Security Scanner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List contents of /app/code and outputs
        run: |
          echo "===== CODE FILES ====="
          find ${{ github.workspace }} -type f
          echo "===== OUTPUT FILES ====="
          ls -al ${{ github.workspace }}/outputs

      - name: Prepare output folder
        run: mkdir -p outputs

      - name: Run Git Security Tool (Gitleaks + Semgrep + YARA)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app/code \
            -v ${{ github.workspace }}/outputs:/app/outputs \
            -v ${{ github.workspace }}/configs:/app/configs \
            -v ${{ github.workspace }}/configs/gitleaks.toml:/gitleaks.toml \
            eliechxh/git-salus-scanner

      - name: Upload Scan Reports
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: outputs/
